name: Flutter CI

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.channel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable, beta]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
